import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ResponsiveContainer } from "@/components/ResponsiveContainer";
import { ViewSwitcher } from "@/components/ViewSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Dedicated Header Area */}
        <header className="w-full bg-white border-b border-gray-200 py-4">
          <div className="flex justify-center">
            <ViewSwitcher 
              variant="dropdown" 
              className="shadow-sm" 
            />
          </div>
        </header>
        
        {/* Main Content */}
        <ResponsiveContainer>
          {children}
        </ResponsiveContainer>
      </body>
    </html>
  );
}
